package ch03;
public class BilanganTertinggi3 {
    public static void main(String[] args) {
        int e = 1;
        int f = 8;
        int g = 5;
        if (f > e) {
            System.out.println("nilai tertinggi = " + f);
        }
        if (e > g) {
            System.out.println("nilai tertinggi =" + e);
        }if (f < g) {
                System.out.println("nilai tertinggi = " + g);
            }
        }

    }
